import type { Settings, Service, PortfolioItem } from "./client"

export const DEFAULT_SETTINGS: Settings = {
  discountPercent: 20,
  contactPhone: "+7 776 100 10 66",
  telegramLink: "https://t.me/+77761001066",
  whatsappLink: "https://wa.me/77761001066?text=Здравствуйте!%20Пишу%20на%20счет%20монтажа/съемки",
  instagramLink: "https://instagram.com/beebars_t",
  heroHeading: "Твое лучшее видео начинается здесь",
  heroSubheading: "Собери свой проект в калькуляторе и успей забронировать дату",
  heroCtaPrimary: "Рассчитать стоимость",
  heroCtaSecondary: "Смотреть портфолио",
  heroStats: [
    { value: "150+", label: "Проектов" },
    { value: "8 лет", label: "Опыта" },
    { value: "48ч", label: "Сроки сдачи" },
  ],
  headerTagline: "Видеопроизводство полного цикла",
}

export const DEFAULT_SERVICES: Service[] = [
  // Wedding
  {
    id: "wedding-day",
    title: "Съемка свадебного дня",
    description: "Ловлю искренние эмоции и масштаб события без лишней постановки",
    price: 160000,
    category: "wedding",
    order: 1,
  },
  {
    id: "wedding-edit",
    title: "Монтаж фильма",
    description: "Кинематографичный фильм и стильный тизер для соцсетей",
    price: 80000,
    category: "wedding",
    order: 2,
  },
  {
    id: "love-story",
    title: "Love Story",
    description: "Ваша личная киноистория с продуманной идеей и локациями",
    price: 70000,
    category: "wedding",
    order: 3,
  },
  {
    id: "video-invite",
    title: "Видео-пригласительное",
    description: "Креативный способ позвать близких в современном формате",
    price: 25000,
    category: "wedding",
    order: 4,
  },
  {
    id: "reels-wedding",
    title: 'Пакет "Reels-Свадьба"',
    description: "Трендовые ролики для Instagram сразу после праздника",
    price: 20000,
    category: "wedding",
    order: 5,
  },
  // Events
  {
    id: "event-shooting",
    title: "Выездная съемка",
    description: "Профессиональный репортаж с идеальным светом и стабилизацией",
    price: 20000,
    category: "events",
    hourly: true,
    order: 1,
  },
  {
    id: "aftermovie",
    title: "Монтаж aftermovie",
    description: "Сочный отчетный ролик под драйвовую музыку",
    price: 30000,
    category: "events",
    order: 2,
  },
  {
    id: "creative-clip",
    title: "Творческий клип",
    description: "Постановочное видео с режиссурой для вау-эффекта",
    price: 50000,
    category: "events",
    order: 3,
  },
  // Social
  {
    id: "script",
    title: "Разработка сценария",
    description: "Цепляющая структура ролика с первых секунд",
    price: 5000,
    category: "social",
    order: 1,
  },
  {
    id: "reels-series",
    title: "Съемка серии Reels",
    description: "Запас качественного контента на месяц за один выезд",
    price: 40000,
    category: "social",
    order: 2,
  },
  {
    id: "vertical-edit",
    title: "Монтаж вертикального видео",
    description: "Динамичная склейка со звуком и трендовыми эффектами",
    price: 8000,
    category: "social",
    order: 3,
  },
  {
    id: "youtube-edit",
    title: "Монтаж YouTube",
    description: "Профессиональный эдиторинг с вырезанными паузами",
    price: 35000,
    category: "social",
    order: 4,
  },
  // Business
  {
    id: "smm-package",
    title: "Комплексный SMM",
    description: "Готовые ролики под ключ для высоких конверсий",
    price: 120000,
    category: "business",
    order: 1,
  },
  {
    id: "promo",
    title: "Промо-ролик",
    description: "Презентабельное видео вашего бизнеса и продукта",
    price: 60000,
    category: "business",
    order: 2,
  },
  {
    id: "target-creative",
    title: "Монтаж креатива",
    description: "Яркий рекламный ролик пробивающий баннерную слепоту",
    price: 15000,
    category: "business",
    order: 3,
  },
]

export const DEFAULT_PORTFOLIO: PortfolioItem[] = [
  {
    id: "1",
    title: "Айдана & Ержан",
    category: "wedding",
    tag: "Свадебный фильм",
    imageUrl: "https://via.placeholder.com/800x600?text=Wedding+1",
    videoUrl: "",
    order: 1,
  },
  {
    id: "2",
    title: "Aftermovie · Almaty Night",
    category: "events",
    tag: "Aftermovie",
    imageUrl: "https://via.placeholder.com/800x600?text=Events+1",
    videoUrl: "",
    order: 2,
  },
  {
    id: "3",
    title: "Reels Pack · Beauty",
    category: "social",
    tag: "Reels серия",
    imageUrl: "https://via.placeholder.com/800x600?text=Social+1",
    videoUrl: "",
    order: 3,
  },
  {
    id: "4",
    title: "Promo · Auto Salon",
    category: "business",
    tag: "Промо-ролик",
    imageUrl: "https://via.placeholder.com/800x600?text=Business+1",
    videoUrl: "",
    order: 4,
  },
  {
    id: "5",
    title: "Love Story · Kapchagai",
    category: "wedding",
    tag: "Love Story",
    imageUrl: "https://via.placeholder.com/800x600?text=Wedding+2",
    videoUrl: "",
    order: 5,
  },
  {
    id: "6",
    title: "Корпоратив · KazTech",
    category: "events",
    tag: "Репортаж",
    imageUrl: "https://via.placeholder.com/800x600?text=Events+2",
    videoUrl: "",
    order: 6,
  },
  {
    id: "7",
    title: "TikTok · Food Brand",
    category: "social",
    tag: "Вертикаль",
    imageUrl: "https://via.placeholder.com/800x600?text=Social+2",
    videoUrl: "",
    order: 7,
  },
  {
    id: "8",
    title: "Бренд · Fitness Club",
    category: "business",
    tag: "SMM-пакет",
    imageUrl: "https://via.placeholder.com/800x600?text=Business+2",
    videoUrl: "",
    order: 8,
  },
]
